# Generated by Django 5.2.4 on 2025-07-17 13:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ConfiguracaoAnalise',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='ElementoQuimico',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=255)),
                ('simbolo', models.CharField(max_length=10, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='ProdutoMatPrima',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=255)),
                ('id_ou_op', models.CharField(max_length=100, unique=True, verbose_name='ID ou OP')),
            ],
        ),
        migrations.CreateModel(
            name='ConfiguracaoElementoDetalhe',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('diluicao1_X', models.DecimalField(decimal_places=4, max_digits=10)),
                ('diluicao1_Y', models.DecimalField(decimal_places=4, max_digits=10)),
                ('diluicao2_X', models.DecimalField(blank=True, decimal_places=4, max_digits=10, null=True)),
                ('diluicao2_Y', models.DecimalField(blank=True, decimal_places=4, max_digits=10, null=True)),
                ('limite_min', models.DecimalField(blank=True, decimal_places=4, max_digits=10, null=True)),
                ('limite_max', models.DecimalField(blank=True, decimal_places=4, max_digits=10, null=True)),
                ('configuracao_analise', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='detalhes_elementos', to='api.configuracaoanalise')),
                ('elemento_quimico', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.elementoquimico')),
            ],
            options={
                'unique_together': {('configuracao_analise', 'elemento_quimico')},
            },
        ),
        migrations.AddField(
            model_name='configuracaoanalise',
            name='elementos',
            field=models.ManyToManyField(related_name='configuracoes_analise', through='api.ConfiguracaoElementoDetalhe', to='api.elementoquimico'),
        ),
        migrations.AddField(
            model_name='configuracaoanalise',
            name='produto_mat_prima',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='configuracoes', to='api.produtomatprima'),
        ),
        migrations.CreateModel(
            name='RegistroAnalise',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_analise', models.DateField()),
                ('analista', models.CharField(max_length=255)),
                ('status', models.CharField(choices=[('EM_ANDAMENTO', 'Em Andamento'), ('CONCLUIDO', 'Concluído'), ('CANCELADO', 'Cancelado')], default='EM_ANDAMENTO', max_length=20)),
                ('produto_mat_prima', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='registros_analise', to='api.produtomatprima')),
            ],
        ),
        migrations.AlterUniqueTogether(
            name='configuracaoanalise',
            unique_together={('produto_mat_prima',)},
        ),
        migrations.CreateModel(
            name='DetalheAnalise',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('massa_pesada', models.DecimalField(blank=True, decimal_places=4, max_digits=10, null=True)),
                ('absorbancia_medida', models.DecimalField(blank=True, decimal_places=4, max_digits=10, null=True)),
                ('resultado', models.DecimalField(blank=True, decimal_places=4, max_digits=10, null=True)),
                ('configuracao_elemento_detalhe', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='detalhes_analise_registrados', to='api.configuracaoelementodetalhe')),
                ('registro_analise', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='detalhes', to='api.registroanalise')),
            ],
            options={
                'unique_together': {('registro_analise', 'configuracao_elemento_detalhe')},
            },
        ),
    ]
