# Generated by Django 5.2.4 on 2025-08-12 13:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
        ('elementos', '0002_alter_configuracaoanalise_options_and_more'),
        ('produtos', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='configuracaoelementodetalhe',
            name='elemento_quimico',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='elementos.elementoquimico'),
        ),
        migrations.AlterField(
            model_name='registroanalise',
            name='produto_mat_prima',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='registros_analise_api', to='produtos.produtomatprima'),
        ),
        migrations.AlterField(
            model_name='configuracaoanalise',
            name='produto_mat_prima',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='configuracoes', to='produtos.produtomatprima'),
        ),
        migrations.AlterField(
            model_name='configuracaoanalise',
            name='elementos',
            field=models.ManyToManyField(related_name='configuracoes_analise', through='api.ConfiguracaoElementoDetalhe', to='elementos.elementoquimico'),
        ),
        migrations.DeleteModel(
            name='ElementoQuimico',
        ),
        migrations.DeleteModel(
            name='ProdutoMatPrima',
        ),
    ]
