# Generated by Django 5.2.4 on 2026-03-27 11:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_alter_configuracaoelementodetalhe_elemento_quimico_and_more'),
        ('elementos', '0003_elementoquimico_simbolo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='configuracaoelementodetalhe',
            name='elemento_quimico',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='configuracoes_elemento_detalhe', to='elementos.elementoquimico'),
        ),
    ]
