# Generated by Django 5.2.4 on 2026-03-27 12:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_alter_configuracaoelementodetalhe_elemento_quimico'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='configuracaoanalise',
            unique_together=set(),
        ),
    ]
