# Generated by Django 5.2.4 on 2026-03-27 15:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_alter_configuracaoanalise_unique_together'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='configuracaoelementodetalhe',
            unique_together=set(),
        ),
    ]
