# Generated by Django 5.2.4 on 2026-03-27 15:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_alter_configuracaoelementodetalhe_unique_together'),
    ]

    operations = [
        migrations.AddField(
            model_name='registroanalise',
            name='veredito',
            field=models.CharField(blank=True, choices=[('APROVADO', 'Aprovado'), ('APROVADO_COM_RESCALVAS', 'Aprovado com ressalvas'), ('REPROVADO', 'Reprovado')], max_length=30, null=True),
        ),
    ]
