# Generated by Django 5.2.4 on 2026-03-27 20:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_registroanalise_veredito'),
    ]

    operations = [
        migrations.AddField(
            model_name='registroanalise',
            name='fornecedor',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='registroanalise',
            name='lote',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='registroanalise',
            name='nf',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
