# Generated by Django 5.2.4 on 2025-07-16 11:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('elementos', '0001_initial'),
        ('produtos', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ConfiguracaoAnalise',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('diluicao1_X', models.DecimalField(blank=True, decimal_places=4, help_text='Diluição 1:X (ex: 100 para 1:100)', max_digits=10, null=True)),
                ('diluicao1_Y', models.DecimalField(blank=True, decimal_places=4, help_text='Fator da diluição 1 (ex: 100 para 1:100)', max_digits=10, null=True)),
                ('diluicao2_X', models.DecimalField(blank=True, decimal_places=4, help_text='Diluição 1:X (ex: 50 para 1:50) - Opcional', max_digits=10, null=True)),
                ('diluicao2_Y', models.DecimalField(blank=True, decimal_places=4, help_text='Fator da diluição 2 (ex: 50 para 1:50) - Opcional', max_digits=10, null=True)),
                ('elemento_quimico', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='configuracoes_gerais_por_elemento', to='elementos.elementoquimico')),
                ('produto_mat_prima', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='configuracoes_gerais_por_produto', to='produtos.produtomatprima')),
            ],
            options={
                'verbose_name': 'Configuração de Análise',
                'verbose_name_plural': 'Configurações de Análises',
                'ordering': ['produto_mat_prima__nome', 'elemento_quimico__nome'],
                'unique_together': {('produto_mat_prima', 'elemento_quimico')},
            },
        ),
    ]
