# Generated by Django 5.2.4 on 2026-03-27 14:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('configuracoes', '0001_initial'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='configuracaoanalise',
            unique_together=set(),
        ),
    ]
