# Generated by Django 5.2.4 on 2026-03-27 15:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('configuracoes', '0002_alter_configuracaoanalise_unique_together'),
    ]

    operations = [
        migrations.AddField(
            model_name='configuracaoanalise',
            name='limite_max',
            field=models.DecimalField(blank=True, decimal_places=4, help_text='Limite máximo', max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='configuracaoanalise',
            name='limite_min',
            field=models.DecimalField(blank=True, decimal_places=4, help_text='Limite mínimo', max_digits=10, null=True),
        ),
    ]
