# Generated by Django 5.2.4 on 2025-07-15 13:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('produtos', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ElementoQuimico',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=255, unique=True, verbose_name='Nome do Elemento Químico')),
            ],
            options={
                'verbose_name': 'Elemento Químico',
                'verbose_name_plural': 'Elementos Químicos',
                'ordering': ['nome'],
            },
        ),
        migrations.CreateModel(
            name='ConfiguracaoAnalise',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('diluicao1_X', models.DecimalField(decimal_places=4, max_digits=10, verbose_name='Diluição 1 - Valor X')),
                ('diluicao1_Y', models.DecimalField(decimal_places=4, max_digits=10, verbose_name='Diluição 1 - Valor Y')),
                ('diluicao2_X', models.DecimalField(blank=True, decimal_places=4, max_digits=10, null=True, verbose_name='Diluição 2 - Valor X')),
                ('diluicao2_Y', models.DecimalField(blank=True, decimal_places=4, max_digits=10, null=True, verbose_name='Diluição 2 - Valor Y')),
                ('produto_mat_prima', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='configuracoes_analise', to='produtos.produtomatprima', verbose_name='Produto/Matéria-Prima')),
                ('elemento_quimico', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='configuracoes_analise', to='elementos.elementoquimico', verbose_name='Elemento Químico')),
            ],
            options={
                'verbose_name': 'Configuração de Análise',
                'verbose_name_plural': 'Configurações de Análises',
                'ordering': ['produto_mat_prima__nome', 'elemento_quimico__nome'],
                'unique_together': {('produto_mat_prima', 'elemento_quimico')},
            },
        ),
    ]
