# Generated by Django 5.2.4 on 2025-07-16 11:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('elementos', '0001_initial'),
        ('produtos', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='configuracaoanalise',
            options={'ordering': ['produto_mat_prima__nome', 'elemento_quimico__nome'], 'verbose_name': 'Configuração de Elemento', 'verbose_name_plural': 'Configurações de Elementos'},
        ),
        migrations.AlterField(
            model_name='configuracaoanalise',
            name='elemento_quimico',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='configuracoes_elementos_por_elemento', to='elementos.elementoquimico'),
        ),
        migrations.AlterField(
            model_name='configuracaoanalise',
            name='produto_mat_prima',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='configuracoes_elementos_por_produto', to='produtos.produtomatprima'),
        ),
    ]
