# Generated by Django 5.2.4 on 2025-09-01 12:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('elementos', '0002_alter_configuracaoanalise_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='elementoquimico',
            name='simbolo',
            field=models.CharField(default='X', max_length=10, verbose_name='Símbolo do Elemento Químico'),
        ),
    ]
