# Generated by Django 5.2.4 on 2025-07-15 13:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('elementos', '0001_initial'),
        ('produtos', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='RegistroAnalise',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_analise', models.DateField(verbose_name='Data da Análise')),
                ('nota_fiscal', models.CharField(blank=True, max_length=255, null=True, verbose_name='Nota Fiscal')),
                ('lote', models.CharField(blank=True, max_length=255, null=True, verbose_name='Lote')),
                ('produto_mat_prima', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='registros_analise', to='produtos.produtomatprima', verbose_name='Produto/Matéria-Prima')),
            ],
            options={
                'verbose_name': 'Registro de Análise',
                'verbose_name_plural': 'Registros de Análises',
                'ordering': ['-data_analise', 'produto_mat_prima__nome'],
            },
        ),
        migrations.CreateModel(
            name='DetalheAnalise',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('diluicao1_massa', models.DecimalField(blank=True, decimal_places=4, max_digits=10, null=True, verbose_name='Diluição 1 - Massa')),
                ('diluicao1_abs', models.DecimalField(blank=True, decimal_places=4, max_digits=10, null=True, verbose_name='Diluição 1 - Absorbância')),
                ('diluicao2_massa', models.DecimalField(blank=True, decimal_places=4, max_digits=10, null=True, verbose_name='Diluição 2 - Massa')),
                ('diluicao2_abs', models.DecimalField(blank=True, decimal_places=4, max_digits=10, null=True, verbose_name='Diluição 2 - Absorbância')),
                ('resultado', models.DecimalField(blank=True, decimal_places=4, max_digits=10, null=True, verbose_name='Resultado Final')),
                ('elemento_quimico', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='elementos.elementoquimico', verbose_name='Elemento Químico')),
                ('registro_analise', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='detalhes', to='analises.registroanalise', verbose_name='Registro de Análise')),
            ],
            options={
                'verbose_name': 'Detalhe da Análise',
                'verbose_name_plural': 'Detalhes da Análise',
                'ordering': ['registro_analise', 'elemento_quimico__nome'],
                'unique_together': {('registro_analise', 'elemento_quimico')},
            },
        ),
    ]
