# Generated by Django 5.2.4 on 2025-07-16 11:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analises', '0001_initial'),
        ('elementos', '0001_initial'),
        ('produtos', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='detalheanalise',
            options={'ordering': ['elemento_quimico__nome'], 'verbose_name': 'Detalhe de Análise', 'verbose_name_plural': 'Detalhes de Análises'},
        ),
        migrations.RemoveField(
            model_name='detalheanalise',
            name='diluicao1_abs',
        ),
        migrations.RemoveField(
            model_name='detalheanalise',
            name='diluicao1_massa',
        ),
        migrations.RemoveField(
            model_name='detalheanalise',
            name='diluicao2_abs',
        ),
        migrations.RemoveField(
            model_name='detalheanalise',
            name='diluicao2_massa',
        ),
        migrations.AddField(
            model_name='detalheanalise',
            name='absorbancia_medida',
            field=models.DecimalField(blank=True, decimal_places=4, help_text='Valor de absorbância lido no equipamento.', max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='detalheanalise',
            name='massa_pesada',
            field=models.DecimalField(blank=True, decimal_places=4, help_text='Massa pesada para a diluição no momento da análise.', max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='registroanalise',
            name='data_producao',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='registroanalise',
            name='data_validade',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='registroanalise',
            name='fornecedor',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='detalheanalise',
            name='elemento_quimico',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='detalhes_analise', to='elementos.elementoquimico'),
        ),
        migrations.AlterField(
            model_name='detalheanalise',
            name='registro_analise',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='detalhes_analise', to='analises.registroanalise'),
        ),
        migrations.AlterField(
            model_name='detalheanalise',
            name='resultado',
            field=models.DecimalField(decimal_places=4, default=0, max_digits=10),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='registroanalise',
            name='data_analise',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='registroanalise',
            name='lote',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='registroanalise',
            name='nota_fiscal',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='registroanalise',
            name='produto_mat_prima',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='registros_analise', to='produtos.produtomatprima'),
        ),
    ]
