# Generated by Django 5.2.4 on 2025-07-16 14:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analises', '0002_alter_detalheanalise_options_and_more'),
        ('elementos', '0002_alter_configuracaoanalise_options_and_more'),
        ('produtos', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='registroanalise',
            options={'ordering': ['-data_analise', 'lote'], 'verbose_name': 'Registro de Análise', 'verbose_name_plural': 'Registros de Análises'},
        ),
        migrations.AddField(
            model_name='registroanalise',
            name='status',
            field=models.CharField(choices=[('EM_ANDAMENTO', 'Em Andamento'), ('CONCLUIDO', 'Concluído'), ('CANCELADO', 'Cancelado')], default='EM_ANDAMENTO', max_length=20, verbose_name='Status da Análise'),
        ),
        migrations.AlterField(
            model_name='detalheanalise',
            name='absorbancia_medida',
            field=models.DecimalField(blank=True, decimal_places=4, max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='detalheanalise',
            name='elemento_quimico',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='detalhes_analise', to='elementos.elementoquimico'),
        ),
        migrations.AlterField(
            model_name='detalheanalise',
            name='massa_pesada',
            field=models.DecimalField(blank=True, decimal_places=4, max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='detalheanalise',
            name='registro_analise',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='detalhes', to='analises.registroanalise'),
        ),
        migrations.AlterField(
            model_name='registroanalise',
            name='produto_mat_prima',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='registros_analise', to='produtos.produtomatprima'),
        ),
    ]
