# Generated by Django 5.2.4 on 2026-02-24 19:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analises', '0003_alter_registroanalise_options_registroanalise_status_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='detalheanalise',
            name='volume_final_diluicao_1',
            field=models.DecimalField(blank=True, decimal_places=4, max_digits=10, null=True, verbose_name='Volume Final da Diluição 1 (mL)'),
        ),
        migrations.AddField(
            model_name='detalheanalise',
            name='volume_final_diluicao_2',
            field=models.DecimalField(blank=True, decimal_places=4, max_digits=10, null=True, verbose_name='Volume Final da Diluição 2 (mL)'),
        ),
        migrations.AddField(
            model_name='detalheanalise',
            name='volume_inicial_diluicao_2',
            field=models.DecimalField(blank=True, decimal_places=4, max_digits=10, null=True, verbose_name='Volume Inicial da Diluição 2 (mL)'),
        ),
    ]
