# Generated by Django 5.2.4 on 2026-02-24 20:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analises', '0004_detalheanalise_volume_final_diluicao_1_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='registroanalise',
            name='id_ou_op',
            field=models.CharField(blank=True, help_text='ID ou OP específico desta análise', max_length=255, null=True, verbose_name='ID ou OP'),
        ),
    ]
