# Generated by Django 5.2.4 on 2025-07-15 13:46

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ProdutoMatPrima',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_ou_op', models.CharField(max_length=255, unique=True, verbose_name='ID ou OP')),
                ('nome', models.CharField(max_length=255, verbose_name='Nome do Produto/Matéria-Prima')),
            ],
            options={
                'verbose_name': 'Produto/Matéria-Prima',
                'verbose_name_plural': 'Produtos/Matérias-Primas',
                'ordering': ['nome'],
            },
        ),
    ]
