# Generated by Django 5.2.4 on 2026-02-24 20:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('produtos', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='produtomatprima',
            name='id_ou_op',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='ID ou OP'),
        ),
    ]
